const base_url = process.env.REACT_APP_BASE_URL;

export const Datasets = `${base_url}/datasets`
export const Authenticate = `${base_url}/authenticate`
export const ProviderDataset = `${base_url}/getProviderDatasets`
export const SampleDescriptors = `${base_url}/SampleDescriptors`
export const SampleTypes = `${base_url}/SampleTypes`
export const Sample = `${base_url}/samples`
export const Dataset = `${base_url}/dataset`
export const SampleData = `${base_url}/getSample`
export const Datatypes = `${base_url}/dataTypes`
export const DatasetFileSaveInfo = `${base_url}/dataset/file/save_info`
export const DatasetFileUpload = `${base_url}/dataset/file/upload`;
export const ExperimentType = `${base_url}/experiment_types`
export const FundingSource = `${base_url}/funding_sources`
export const Keyword = `${base_url}/keywords`
export const PaperID = `${base_url}/paper_meta_data`
export const Provider = `${base_url}/getProvider`
export const Dashboard = `${base_url}/dashboard`
export const Setting = `${base_url}/get_settings`
export const Password = `${base_url}/change_password`;